<a href="https://colab.research.google.com/github/youssafB/PyTorch-Learning/blob/main/2_dataset_dataloaders.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from torch.utils.data import DataLoader

In [1]:
!git --version


git version 2.34.1


In [2]:
!git clone https://github.com/youssafB/PyTorch-Learning.git

Cloning into 'PyTorch-Learning'...
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 7 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (7/7), done.


In [3]:
from google.colab import drive
drive.mount('/content/drive')



Mounted at /content/drive


In [6]:
!git commit -m "Added 2_dataset_dataloaders notebook to 1_Basics folder"


fatal: not a git repository (or any of the parent directories): .git


- The **`DataLoader`** in PyTorch is designed to simplify data handling by automating:
  - Batching
  - Shuffling
  - Parallel loading
- To achieve this, it relies on the ability to access individual data samples using **indexing** (e.g., `dataset[idx]`).


**1- intutive way**

-**Step 1: Requirment** Embed your data in a class and define the `__getitem__` method to retrieve an individual element.


In [ ]:
class MyCustomDataset:
    def __init__(self, data):
        self.data = data

    def __getitem__(self, idx):
        return self.data[idx]


In [ ]:
my_dataset = MyCustomDataset([1,2,3,4,5,6])

In [ ]:
my_dataset[2]

3

- By using the `__getitem__` function, you give  your custom class the propty to use `[]` to do somthing .
- This syntax is the standard way in Python to fetch a single element.
- It's commonly used with sequences like lists and dictionaries.
- but You can use it however you want in your class not only to fetch individual elements  for examle return print('hello ysf:',self.data[idx]) but not a standard way to  .




**Step 2** benifit form dataloder

In [ ]:
data_loader = DataLoader(my_dataset, batch_size=2)

In [ ]:

for batch in data_loader:
    print(batch)
    print(batch.shape)

tensor([1, 2])
torch.Size([2])
tensor([3, 4])
torch.Size([2])
tensor([5, 6])
torch.Size([2])


**2 Standard way.** To make things standardized and potentially benefit from other utilities, it’s better to inherit from an already existing class like `Dataset`, where you can inherit the `__getitem__` method and other methodes.

In [ ]:
from torch.utils.data import Dataset
class MyCustomDataset(Dataset):
    def __init__(self, data):
        self.data = data

    def __getitem__(self, idx):
        return self.data[idx]

    def __len__(self):
        return len(self.data)

3 other benfit can be done in  MyCustomDataset
Another key advantage of using this class is the ability to define transformations. With this approach, you can apply transformations to your data on the fly, making your data handling more efficient and flexible.

Transforms in PyTorch are designed to be composable:

You can chain multiple transformations together using transforms.Compose.
The same transform pipeline can be reused across multiple datasets, ensuring consistency.

** Example 1 :**

In [ ]:
from torchvision import transforms

image_transforms = transforms.Compose([
    transforms.Resize((128, 128)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.5], std=[0.5])
])

class ImageDataset(Dataset):
    def __init__(self, image_paths, transform=None):
        self.image_paths = image_paths
        self.transform = transform

    def __getitem__(self, idx):
        image = PIL.Image.open(self.image_paths[idx])
        if self.transform:
            image = self.transform(image)
        return image


In [ ]:
from torchvision import transforms

train_transforms = transforms.Compose([
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(10),
    transforms.ToTensor()
])

train_dataset = ImageDataset(train_image_paths, transform=train_transforms)
